version: '3.8'

services:
  db:
    image: postgres:13
    container_name: helpdesk-db
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: helpdesk-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: your_db
      JWT_SECRET: "your_jwt_secret"
    depends_on:
      - db
    command: sh -c "sleep 5 && /root/helpdesk-api"

  frontend:
    build: ./frontend
    container_name: helpdesk-frontend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - app

volumes:
  postgres_data: